In [19]:
import numpy as np
import pandas as pd

In [22]:
weather=pd.read_csv('weatherAUS.csv')
weather.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0           W           44.0          W      ...             22.0   
1         WNW           44.0        NNW      ...             25.0   
2         WSW           46.0          W      ...             30.0   
3          NE           24.0         SE      ...             16.0   
4           W           41.0        ENE      ...             33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  RainTomorrow  
0      0.0            No  
1      0.0            No  
2      0.0            No  
3      1.0            No  
4      0.2            No  

[5 rows x 24 columns]

In [23]:
weather.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000   
mean       12.194034      23.221348       2.360918      5.468232   
std         6.398495       7.119049       8.478060      4.193704   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.900000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000   
mean       7.611178      40.035230      14.043426      18.662657   
std        3.785483      13.607062       8.915375       8.809800   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.800000      31.000000       7.000000      13.000000   
50%        8.400000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000   
mean       68.880831      51.539116    1017.64994    1015.255889   
std        19.029164      20.795902       7.10653       7.037414   
min         0.000000       0.000000     980.50000     977.100000   
25%        57.000000      37.000000    1012.90000    1010.400000   
50%        70.000000      52.000000    1017.60000    1015.200000   
75%        83.000000      66.000000    1022.40000    1020.000000   
max       100.000000     100.000000    1041.00000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am       Temp3pm        RISK_MM  
count  89572.000000  86102.000000  143693.000000  141851.00000  142193.000000  
mean       4.447461      4.509930      16.990631      21.68339       2.360682  
std        2.887159      2.720357       6.488753       6.93665       8.477969  
min        0.000000      0.000000      -7.200000      -5.40000       0.000000  
25%        1.000000      2.000000      12.300000      16.60000       0.000000  
50%        5.000000      5.000000      16.700000      21.10000       0.000000  
75%        7.000000      7.000000      21.600000      26.40000       0.800000  
max        9.000000      9.000000      40.200000      46.70000     371.000000

In [24]:
np.sum(weather.isnull())

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RISK_MM           3267
RainTomorrow      3267
dtype: int64

In [26]:
weather['MinTemp']=weather['MinTemp'].fillna((weather['MinTemp'].mean()))
weather['MaxTemp']=weather['MaxTemp'].fillna((weather['MaxTemp'].mean()))
weather['Rainfall']=weather['Rainfall'].fillna((weather['Rainfall'].mean()))
weather['Evaporation']=weather['Evaporation'].fillna((weather['Evaporation'].mean()))
weather['Sunshine']=weather['Sunshine'].fillna((weather['Sunshine'].mean()))
weather['WindGustSpeed']=weather['WindGustSpeed'].fillna((weather['WindGustSpeed'].mean()))
weather['WindSpeed9am']=weather['WindSpeed9am'].fillna((weather['WindSpeed9am'].mean()))
weather['WindSpeed3pm']=weather['WindSpeed3pm'].fillna((weather['WindSpeed3pm'].mean()))
weather['Humidity9am']=weather['Humidity9am'].fillna((weather['Humidity9am'].mean()))
weather['Humidity3pm']=weather['Humidity3pm'].fillna((weather['Humidity3pm'].mean()))
weather['Pressure9am']=weather['Pressure9am'].fillna((weather['Pressure9am'].mean()))
weather['Pressure3pm']=weather['Pressure3pm'].fillna((weather['Pressure3pm'].mean()))
weather['Cloud9am']=weather['Cloud9am'].fillna((weather['Cloud9am'].mean()))
weather['Cloud3pm']=weather['Cloud3pm'].fillna((weather['Cloud3pm'].mean()))
weather['Temp9am']=weather['Temp9am'].fillna((weather['Temp9am'].mean()))
weather['Temp3pm']=weather['Temp3pm'].fillna((weather['Temp3pm'].mean()))
weather['RISK_MM']=weather['RISK_MM'].fillna((weather['RISK_MM'].mean()))
np.sum(weather.isnull())

Date                 0
Location             0
MinTemp              0
MaxTemp              0
Rainfall             0
Evaporation          0
Sunshine             0
WindGustDir      10326
WindGustSpeed        0
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am         0
WindSpeed3pm         0
Humidity9am          0
Humidity3pm          0
Pressure9am          0
Pressure3pm          0
Cloud9am             0
Cloud3pm             0
Temp9am              0
Temp3pm              0
RainToday         3261
RISK_MM              0
RainTomorrow      3267
dtype: int64

In [27]:
from scipy.stats import mode

In [28]:
weather['WindGustDir']=weather['WindGustDir'].fillna(weather['WindGustDir']).dropna().mode()[0]
weather['WindDir9am']=weather['WindDir9am'].fillna(weather['WindDir9am']).dropna().mode()[0]
weather['WindDir3pm']=weather['WindDir3pm'].fillna(weather['WindDir3pm']).dropna().mode()[0]
weather['RainToday']=weather['RainToday'].fillna(weather['RainToday']).dropna().mode()[0]
weather['RainTomorrow']=weather['RainTomorrow'].fillna(weather['RainTomorrow']).dropna().mode()[0]
np.sum(weather.isnull())

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [41]:
weather.to_csv( "weather (tanpa missing value).csv", index=False )

In [76]:
weather1=pd.read_csv('weather (tanpa missing value).csv')
weather1.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6     5.468232  7.611178   
1  2008-12-02   Albury      7.4     25.1       0.0     5.468232  7.611178   
2  2008-12-03   Albury     12.9     25.7       0.0     5.468232  7.611178   
3  2008-12-04   Albury      9.2     28.0       0.0     5.468232  7.611178   
4  2008-12-05   Albury     17.5     32.3       1.0     5.468232  7.611178   

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0           W           44.0          N      ...             22.0   
1           W           44.0          N      ...             25.0   
2           W           46.0          N      ...             30.0   
3           W           24.0          N      ...             16.0   
4           W           41.0          N      ...             33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1  8.000000   4.50993     16.9     21.8         No   
1       1010.6       1007.8  4.447461   4.50993     17.2     24.3         No   
2       1007.6       1008.7  4.447461   2.00000     21.0     23.2         No   
3       1017.6       1012.8  4.447461   4.50993     18.1     26.5         No   
4       1010.8       1006.0  7.000000   8.00000     17.8     29.7         No   

   RISK_MM  RainTomorrow  
0      0.0            No  
1      0.0            No  
2      0.0            No  
3      1.0            No  
4      0.2            No  

[5 rows x 24 columns]

In [84]:
from scipy import stats

In [85]:
weather2=weather1.drop(['Location','WindGustDir','WindDir9am','WindDir3pm','RainToday','RainTomorrow'],1)
z=np.abs(stats.zscore(weather2._get_numeric_data()))
print(z)

[[0.2839081  0.05106236 0.05066749 ... 0.03566603 0.00324671 0.41818778]
 [0.67741422 0.27902073 0.42846558 ... 0.083768   0.39211469 0.41818778]
 [0.20379791 0.36904339 0.42846558 ... 0.6930597  0.22101278 0.41818778]
 ...
 [0.997855   0.54908871 0.42846558 ... 0.66982962 0.67209965 0.41818778]
 [0.61332607 0.56409248 0.42846558 ... 0.25294583 0.65654493 0.41818778]
 [0.52423868 0.00284798 0.42846558 ... 0.26897982 0.13674577 1.54810522]]


In [86]:
weather3=weather1[(z < 3).all(axis=1)]
print(weather3.shape)

(104273, 24)


In [87]:
weather3.to_csv( "weather (tanpa missing value dan outlier).csv", index=False )

### Transformasi Data

In [94]:
weather4=pd.read_csv("weather (tanpa missing value dan outlier).csv")
weather4=weather4.drop(['Date','Location','WindGustDir','WindDir9am','WindDir3pm','RainToday','RainTomorrow'],1)
weather4.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0     13.4     22.9       0.6     5.468232  7.611178           44.0   
1      7.4     25.1       0.0     5.468232  7.611178           44.0   
2     12.9     25.7       0.0     5.468232  7.611178           46.0   
3      9.2     28.0       0.0     5.468232  7.611178           24.0   
4     17.5     32.3       1.0     5.468232  7.611178           41.0   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0          20.0          24.0         71.0         22.0       1007.7   
1           4.0          22.0         44.0         25.0       1010.6   
2          19.0          26.0         38.0         30.0       1007.6   
3          11.0           9.0         45.0         16.0       1017.6   
4           7.0          20.0         82.0         33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RISK_MM  
0       1007.1  8.000000   4.50993     16.9     21.8      0.0  
1       1007.8  4.447461   4.50993     17.2     24.3      0.0  
2       1008.7  4.447461   2.00000     21.0     23.2      0.0  
3       1012.8  4.447461   4.50993     18.1     26.5      1.0  
4       1006.0  7.000000   8.00000     17.8     29.7      0.2

In [97]:
#Normalisasi
from sklearn.preprocessing import normalize
weather4norm=normalize(weather4,norm='l2') #default norm l2, lainnya L1 dan Max
weather4norm=pd.DataFrame(weather4norm)
weather4norm.tail()

0         1         2         3         4         5         6   \
0  0.009382  0.016034  0.000420  0.003829  0.005329  0.030808  0.014004   
1  0.005176  0.017558  0.000000  0.003825  0.005324  0.030778  0.002798   
2  0.009031  0.017993  0.000000  0.003828  0.005329  0.032205  0.013302   
3  0.006400  0.019478  0.000000  0.003804  0.005295  0.016696  0.007652   
4  0.012233  0.022579  0.000699  0.003822  0.005320  0.028660  0.004893   

         7         8         9         10        11        12        13  \
0  0.016804  0.049713  0.015404  0.705568  0.705148  0.005601  0.003158   
1  0.015389  0.030778  0.017488  0.706926  0.704967  0.003111  0.003155   
2  0.018203  0.026604  0.021003  0.705435  0.706206  0.003114  0.001400   
3  0.006261  0.031305  0.011131  0.707904  0.704564  0.003094  0.003137   
4  0.013981  0.057321  0.023068  0.706586  0.703231  0.004893  0.005592   

         14        15        16  
0  0.011833  0.015264  0.000000  
1  0.012032  0.016998  0.000000  
2  0.014702  0.016243  0.000000  
3  0.012591  0.018435  0.000696  
4  0.012443  0.020761  0.000140

### Feature Selection 

In [108]:
weather5=weather3.drop(['Date','Location'],1)

In [109]:
from sklearn.feature_selection import SelectKBest, chi2, f_regression
weather_x=weather5.drop(columns=['RainTomorrow'])
weather_y=weather5[['RainTomorrow']]
selector=SelectKBest(f_regression, k="all").fit(weather_x,weather_y)
weather_new=selector.transform(weather_x)
score=selector.scores_
score

ValueError: could not convert string to float: 'W'