## Tugas Regresi

### Mengatasi Missing Value

In [107]:
import numpy as np
import pandas as pd

In [108]:
real_es=pd.read_csv('Real estate.csv')
real_es.head()

No  X1 house age  X2 distance to the nearest MRT station  \
0   1          32.0                                84.87882   
1   2          19.5                               306.59470   
2   3          13.3                               561.98450   
3   4          13.3                               561.98450   
4   5           5.0                               390.56840   

   X3 number of convenience stores  X4 latitude  X5 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [109]:
real_es.describe()

No  X1 house age  X2 distance to the nearest MRT station  \
count  414.000000    397.000000                              414.000000   
mean   207.500000     18.471033                             1083.885689   
std    119.655756     11.014322                             1262.109595   
min      1.000000      1.000000                               23.382840   
25%    104.250000     10.800000                              289.324800   
50%    207.500000     16.300000                              492.231300   
75%    310.750000     29.300000                             1454.279000   
max    414.000000     43.800000                             6488.021000   

       X3 number of convenience stores  X4 latitude  X5 longitude  \
count                       414.000000   414.000000    414.000000   
mean                          4.094203    24.969030    121.533361   
std                           2.945562     0.012410      0.015347   
min                           0.000000    24.932070    121.473530   
25%                           1.000000    24.963000    121.528085   
50%                           4.000000    24.971100    121.538630   
75%                           6.000000    24.977455    121.543305   
max                          10.000000    25.014590    121.566270   

       Y house price of unit area  
count                  414.000000  
mean                    37.980193  
std                     13.606488  
min                      7.600000  
25%                     27.700000  
50%                     38.450000  
75%                     46.600000  
max                    117.500000

In [110]:
np.sum(real_es.isnull())

No                                         0
X1 house age                              17
X2 distance to the nearest MRT station     0
X3 number of convenience stores            0
X4 latitude                                0
X5 longitude                               0
Y house price of unit area                 0
dtype: int64

In [112]:
real_es['X1 house age']=real_es['X1 house age'].fillna((real_es['X1 house age'].mean()))
np.sum(real_es.isnull())

No                                        0
X1 house age                              0
X2 distance to the nearest MRT station    0
X3 number of convenience stores           0
X4 latitude                               0
X5 longitude                              0
Y house price of unit area                0
dtype: int64

In [113]:
real_es.to_csv( "real_es (tanpa missing value).csv", index=False ) #data tanpa missing value

### Mengatasi Data yang Missing Value dan Outlier

In [114]:
from scipy import stats

In [115]:
real_es1=pd.read_csv('real_es (tanpa missing value).csv') #data dengan missing value sudah diatasi
real_es1.head()

No  X1 house age  X2 distance to the nearest MRT station  \
0   1          32.0                                84.87882   
1   2          19.5                               306.59470   
2   3          13.3                               561.98450   
3   4          13.3                               561.98450   
4   5           5.0                               390.56840   

   X3 number of convenience stores  X4 latitude  X5 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [116]:
z=np.abs(stats.zscore(real_es1._get_numeric_data()))
print(z)

[[1.72787215 1.25591268 0.79249504 ... 1.12542986 0.44876222 0.00590088]
 [1.71950473 0.09552045 0.61661163 ... 0.91244418 0.40113894 0.3105072 ]
 [1.71113731 0.4800341  0.41401527 ... 1.48686011 0.68818339 0.6857819 ]
 ...
 [1.71113731 0.03053848 0.54967846 ... 0.82289338 0.42397202 0.19277396]
 [1.71950473 0.96275726 0.77668389 ... 0.18475479 0.4768143  1.06841493]
 [1.72787215 1.11128747 0.78807071 ... 0.42757905 0.63534112 1.90726426]]


In [117]:
real_es1=real_es1[(z < 3).all(axis=1)]
real_es1.head()

No  X1 house age  X2 distance to the nearest MRT station  \
0   1          32.0                                84.87882   
1   2          19.5                               306.59470   
2   3          13.3                               561.98450   
3   4          13.3                               561.98450   
4   5           5.0                               390.56840   

   X3 number of convenience stores  X4 latitude  X5 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [118]:
real_es1.to_csv( "real_es1 (tanpa missing value & outlier).csv", index=False ) #data tanpa missing value dan outlier

### Mengatasi Data yang Missing Value dan Melakukan Transformasi 

In [119]:
import pandas as pd
import numpy as np

In [134]:
real_es2=pd.read_csv('real_es (tanpa missing value).csv') #data dengan missing value sudah diatasi
real_es2=real_es2.iloc[0:415,1:7]
real_es2.head()

X1 house age  X2 distance to the nearest MRT station  \
0          32.0                                84.87882   
1          19.5                               306.59470   
2          13.3                               561.98450   
3          13.3                               561.98450   
4           5.0                               390.56840   

   X3 number of convenience stores  X4 latitude  X5 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [135]:
#Normalisasi
from sklearn.preprocessing import normalize
real_es2_norm=normalize(real_es2,norm='l2') #default norm l2, lainnya L1 dan Max
real_es2_norm=pd.DataFrame(real_es2_norm)
real_es2_norm.head()

0         1         2         3         4         5
0  0.201737  0.535100  0.063043  0.157500  0.766225  0.238933
1  0.058362  0.917610  0.026936  0.074764  0.363757  0.126301
2  0.023025  0.972905  0.008656  0.043258  0.210416  0.081886
3  0.022999  0.971790  0.008646  0.043209  0.210175  0.094761
4  0.012132  0.947692  0.012132  0.060611  0.294916  0.104580

In [136]:
real_es2_norm.to_csv( "real_es2 (tanpa missing value & ditransformasi).csv", index=False ) #data tanpa missing value dan ditransformasi

### Mengatasi Data yang Missing Value, Outlier, dan Melakukan Transformasi 

In [137]:
import pandas as pd
import numpy as np

In [140]:
real_es3=pd.read_csv('real_es1 (tanpa missing value & outlier).csv') #data dengan missing value dan outlier sudah diatasi
real_es3=real_es3.iloc[0:415,1:7]
real_es3.head()

X1 house age  X2 distance to the nearest MRT station  \
0          32.0                                84.87882   
1          19.5                               306.59470   
2          13.3                               561.98450   
3          13.3                               561.98450   
4           5.0                               390.56840   

   X3 number of convenience stores  X4 latitude  X5 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [141]:
#Normalisasi
from sklearn.preprocessing import normalize
real_es3_norm=normalize(real_es3,norm='l2') #default norm l2, lainnya L1 dan Max
real_es3_norm=pd.DataFrame(real_es3_norm)
real_es3_norm.head()

0         1         2         3         4         5
0  0.201737  0.535100  0.063043  0.157500  0.766225  0.238933
1  0.058362  0.917610  0.026936  0.074764  0.363757  0.126301
2  0.023025  0.972905  0.008656  0.043258  0.210416  0.081886
3  0.022999  0.971790  0.008646  0.043209  0.210175  0.094761
4  0.012132  0.947692  0.012132  0.060611  0.294916  0.104580

In [142]:
real_es3_norm.to_csv( "real_es3 (tanpa missing value, outlier, & ditransformasi).csv", index=False ) #data tanpa missing value, outlier, dan ditransformasi